Upload Photo UI/UX Implementation
unsri-hackers/ecommerce-mobile pull request #65
Opened 2021-07-03 12:25 UTC by Farrize

Implementing UI/UX to Product Photo Page
Updating Model to match API Spec
Using Cloudinary for Image Upload 
Updating Image Picker library to use Multi Image Picker new feature

2021-07-03 14:54 UTC, ichsanachmad requested changes

2021-07-03 14:54 UTC, ichsanachmad commented on lib/views/screens/upload_screen/pages.dart
>  class UploadScreen extends StatefulWidget {
Tolong di add loading state ketika melakukan upload item pada tombol "Save" dan jika upload berhasil lakukan pop

2021-07-03 14:54 UTC, ichsanachmad commented on pubspec.yaml
> +  cloudinary_public: ^0.8.1+1
Tolong sort by name

2021-07-04 01:09 UTC, merged

2021-07-04 01:09 UTC, ariefwijaya commented
Nanti PR lagi aja ya @Farrize